import {readFile,mkdir,writeFile} from 'node:fs/promises';
const out=new URL('../dist/',import.meta.url);await mkdir(out,{recursive:true});
const assets=JSON.parse(await readFile(new URL('../assets.json',import.meta.url),'utf8'));
const phone='090-5238-1332',tel='tel:09052381332',instagram='https://www.instagram.com/tamayama_junko/';
const map='https://maps.app.goo.gl/GoVsk32LAZ3YRfVz6?g_st=il';
const facebook='https://www.facebook.com/share/1FUNmEGgBb/?mibextid=wwXIfr';
const ext='target="_blank" rel="noopener noreferrer"';
const arrow='<span aria-hidden="true">↗</span>';
const ig='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.6" cy="6.5" r=".7" fill="currentColor"/></svg>';
const pin='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>';
const fb='<span class="facebook-symbol" aria-hidden="true">f</span>';
const socialLinks=(buttons=false)=>`<div class="${buttons?'social-buttons':'social-links'}" aria-label="玉の家の外部ページ"><a class="${buttons?'button':'social-link'}" href="${instagram}" ${ext}>${ig}<span>Instagram${buttons?'を見る':''}</span>${arrow}</a><a class="${buttons?'button social-button-secondary':'social-link'}" href="${map}" ${ext}>${pin}<span>Googleマップ${buttons?'を見る':''}</span>${arrow}</a><a class="${buttons?'button social-button-secondary':'social-link'}" href="${facebook}" ${ext}>${fb}<span>Facebook${buttons?'を見る':''}</span>${arrow}</a></div>`;
const brand='<img src="assets/logo.webp" width="240" height="240" alt=""><span><small>居酒屋カラオケ</small><strong>玉の家</strong></span>';
function photo(name,alt,{cls='',eager=false,sizes='(max-width: 760px) 100vw, 50vw'}={}){const a=assets[name];return `<img class="${cls}" src="assets/${name}.webp" ${a.width>640&&name!=='board'?`srcset="assets/${name}-640.webp 640w, assets/${name}.webp ${a.width}w" sizes="${sizes}"`:''} width="${a.width}" height="${a.height}" alt="${alt}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
const navItems=[['index.html#about','玉の家について'],['menu.html','お料理・お酒'],['karaoke.html','カラオケ・店内'],['access.html','店舗案内']];
const nav=page=>navItems.map(([url,label])=>`<a href="${url}"${page===url?' aria-current="page"':''}>${label}</a>`).join('');
const header=page=>`<a class="skip" href="#main">本文へ</a><header class="header"><a class="brand" href="index.html" aria-label="居酒屋カラオケ玉の家 トップ">${brand}</a><nav aria-label="メインナビゲーション">${nav(page)}</nav><a class="header-phone" href="${tel}"><span>ご予約・お問い合わせ</span>${phone}</a><button class="menu-toggle" aria-label="メニューを開く" aria-controls="mobile-menu" aria-expanded="false"><span></span><span></span><small>MENU</small></button></header><dialog id="mobile-menu" aria-labelledby="mobile-title"><div class="dialog-top"><p id="mobile-title">玉の家</p><button class="menu-close" aria-label="メニューを閉じる">閉じる ×</button></div><nav aria-label="スマートフォンメニュー"><a href="index.html">トップ</a>${nav(page)}</nav><a class="button" href="${tel}">電話でご予約 ${arrow}</a><p>17:00–24:00 ／ 月曜・木曜 定休</p></dialog>`;
const reserve=`<section class="reserve section" id="reservation"><div><p class="eyebrow">COME ON IN</p><h2>今夜、玉の家で。</h2><p>お席のご予約・お問い合わせは、お電話で。<br>おひとりでも、みんなでも。お待ちしています。</p></div><a class="reserve-call" href="${tel}"><span>ご予約・お問い合わせ</span><strong>${phone}</strong><small>営業時間 17:00–24:00 ／ 月曜・木曜 定休</small></a></section>`;
const footer=page=>`<footer class="footer"><div class="footer-main"><a class="brand" href="index.html" aria-label="居酒屋カラオケ玉の家 トップ">${brand}</a><div><p>〒223-0065 神奈川県横浜市港北区高田東4丁目11-16<br>たかな橋荘 101</p><p>高田駅から徒歩10分</p></div>${socialLinks()}</div><div class="footer-bottom"><nav aria-label="フッターナビゲーション">${nav(page)}</nav><small>© 居酒屋カラオケ玉の家</small></div></footer><div class="mobile-contact"><a href="${map}" ${ext}>アクセス ${arrow}</a><a href="${tel}">電話でご予約 <span aria-hidden="true">↗</span></a></div>`;
function document(title,description,body,page){return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#e7b45f"><title>${title}｜居酒屋カラオケ玉の家</title><meta name="description" content="${description}"><meta property="og:title" content="${title}｜居酒屋カラオケ玉の家"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><meta property="og:locale" content="ja_JP"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='32' fill='%23e7b45f'/%3E%3Ctext x='32' y='47' text-anchor='middle' font-size='46' font-family='serif' fill='%2324231f'%3E玉%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="assets/style.css"><script src="assets/site.js" defer></script></head><body>${header(page)}<main id="main">${body}${reserve}</main>${footer(page)}</body></html>`;}
const pages={};
pages['index.html']=document('歌って、食べて、笑って。','横浜・高田駅から徒歩10分。音響にこだわったカラオケと手作り料理、お酒を楽しむ16席の居酒屋です。ご予約は090-5238-1332。',`
<section class="hero" id="top"><div class="hero-copy"><p class="eyebrow">YOKOHAMA · TAKATA / SINCE 2018</p><h1>歌って、<br>食べて、<br><span>笑って。</span></h1><p class="hero-lead">好きな歌と、おいしい一皿。<br>いつの間にか、みんな笑顔。</p><a class="text-link" href="#about">ようこそ、玉の家へ <span aria-hidden="true">↓</span></a></div><div class="hero-visual"><div class="hero-main">${photo('counter','お酒のボトルと木の温もりに囲まれた玉の家のカウンター',{eager:true})}</div><figure class="hero-inset">${photo('karaoke','玉の家の赤と白のマイクとカラオケ端末',{eager:true,sizes:'230px'})}<figcaption>今日の一曲、何にする？</figcaption></figure><span class="hero-side">IZAKAYA & KARAOKE TAMANOIE</span></div></section>
<div class="opening-strip"><p>横浜・高田の、歌える居酒屋。</p><p><span>OPEN</span> 17:00–24:00 <i></i> 月曜・木曜 定休</p></div>
<section class="intro section" id="about"><p class="eyebrow">A GOOD SONG. A GOOD EVENING.</p><div class="intro-grid"><h2>はじめまして、も。<br>いつもの、も。</h2><div><p>誰かが歌えば、自然と拍手が生まれる。<br>料理を囲めば、何気ない会話がはずむ。</p><p>2018年7月24日、玉の家はオープンしました。<br>大切にしているのは、歌と料理と、<br>人と人がつながる温かな時間です。</p><p>思いきり歌いたい夜も、ゆっくり飲みたい夜も。<br>どうぞ、気負わずお立ち寄りください。</p></div></div></section>`,'index.html');
const homeMore=`
<section class="song-section section"><div class="song-picture reveal">${photo('karaoke','気持ちよく歌える玉の家のカラオケ設備')}<span class="image-caption">YOUR SONG, OUR GOOD TIME.</span></div><div class="song-copy reveal"><p class="eyebrow">01 / SING TOGETHER</p><h2>あなたの一曲で、<br>今夜がはじまる。</h2><p>音響にもこだわった、気持ちよく歌えるカラオケ。<br>懐かしい曲も、お気に入りの曲も。</p><p>歌う人も、聴く人も、一緒になって楽しめる。<br>初めての方も入りやすい、温かな空気を大切にしています。</p><a class="text-link" href="karaoke.html">カラオケと店内のご案内 <span aria-hidden="true">→</span></a></div></section>
<section class="food-section section"><div class="section-heading"><div><p class="eyebrow">02 / EAT & DRINK</p><h2>歌の合間に、<br>おいしい時間。</h2></div><p>一品一品、心を込めて手作り。<br>お酒のお供にも、しっかり食べたい夜にも。</p></div><div class="food-grid"><a class="food-card reveal" href="menu.html#food">${photo('karaage','玉の家の鶏の唐揚げ',{sizes:'(max-width: 760px) 88vw, 30vw'})}<div><span>お店の定番</span><h3>メガとり唐</h3><p>一個から、気軽につまめる一品。</p><small>1個 150円</small></div></a><a class="food-card reveal" href="menu.html#food">${photo('beef','スキレットで提供する牛焼肉',{sizes:'(max-width: 760px) 88vw, 30vw'})}<div><span>お腹も、心も</span><h3>スキレット牛焼肉</h3><p>しっかり食べたい夜のお供に。</p><small>700円</small></div></a><a class="food-card reveal" href="menu.html#food">${photo('noodles','牛肉と野菜を使った焼そば',{sizes:'(max-width: 760px) 88vw, 30vw'})}<div><span>もうひと皿</span><h3>牛焼そば</h3><p>お酒の後にも、食事の一皿にも。</p><small>700円</small></div></a></div><div class="center-link"><a class="text-link" href="menu.html">お料理・お酒のお品書き <span aria-hidden="true">→</span></a></div></section>
<section class="space-section section"><div class="space-copy reveal"><p class="eyebrow">03 / MAKE YOURSELF AT HOME</p><h2>気づけば、<br>いつもの居場所に。</h2><p>カウンターでひとり、ゆっくり一杯。<br>テーブルを囲んで、友人たちと乾杯。</p><p>全16席の、顔が見える距離感。<br>歌って、食べて、笑って過ごす夜をどうぞ。</p><a class="text-link" href="karaoke.html#seats">お席のご案内 <span aria-hidden="true">→</span></a></div><div class="space-photo reveal">${photo('room','カウンターとテーブル席が並ぶ玉の家の店内')}<span class="seat-tag">COUNTER & TABLE / 16 SEATS</span></div></section>
<section class="instagram-section section"><div class="instagram-copy"><p class="eyebrow">FOLLOW & VISIT</p><h2>玉の家の、日々。</h2><p>日々のお知らせは<br>Instagram・Facebookへ。<br>アクセスはGoogleマップから。</p>${socialLinks(true)}</div><div class="instagram-photos"><a href="${instagram}" ${ext} aria-label="玉の家のInstagramへ：お酒とお店の様子">${photo('bottles','玉の家に並ぶお酒のボトル')}</a><a href="${instagram}" ${ext} aria-label="玉の家のInstagramへ：料理と日々のお知らせ">${photo('salad','彩り豊かな春雨サラダ')}</a></div></section>`;
pages['index.html']=pages['index.html'].replace(reserve,homeMore+reserve);
const heading=(en,title,copy)=>`<section class="page-heading"><p class="eyebrow">${en}</p><h1>${title}</h1><p>${copy}</p></section>`;
const rows=items=>`<dl class="price-list">${items.map(([name,price])=>`<div><dt>${name}</dt><dd>${price}</dd></div>`).join('')}</dl>`;
pages['menu.html']=document('お料理・お酒','心を込めた手作り料理と、お好きなお酒。玉の家のお品書きと晩酌セットをご紹介します。',`
${heading('FOOD & DRINK','お料理・お酒','歌の合間に、おいしいひととき。')}
<section class="menu-intro section"><div class="menu-main-photo reveal">${photo('beef','玉の家のスキレット牛焼肉',{eager:true})}</div><div class="menu-intro-copy reveal"><p class="eyebrow">HOMEMADE, WITH CARE</p><h2>手作りの一皿と、<br>お好きな一杯。</h2><p>お料理は、一品一品心を込めて。<br>家庭的で温かみのある味を、ご用意しています。</p><p>「今日は何があるかな？」<br>そんな楽しみも、玉の家の時間のひとつです。</p><div class="set-box"><span>まずは、気軽に</span><h3>晩酌セット <strong>1,000<small>円</small></strong></h3><p>2品盛り ＋ 1ドリンク<br>〈生ビール・日本酒・ワイン〉</p></div></div></section>
<nav class="category-nav" aria-label="お品書きのカテゴリー"><a href="#food">お料理</a><a href="#drink">お酒</a><a href="#blackboard">店内のお品書き</a></nav>
<section class="menu-section section" id="food"><div class="section-heading"><div><p class="eyebrow">OUR MENU</p><h2>お料理のお品書き</h2></div><p class="note">店内メニューに記載の価格です。<br>内容・価格は変わる場合があります。最新の内容は店頭でご確認ください。</p></div><div class="menu-columns">
<section class="menu-group reveal"><h3>まずは一品</h3>${rows([['メガとり唐（1個）','150円'],['ヤゲン唐','350円'],['ポテトフライ','350円'],['ゆかりキューリ','350円'],['青唐胡瓜味噌漬け','250円'],['トマト','350円'],['イカ塩辛・酒盗','各350円'],['あたりめ','450円']])}</section>
<section class="menu-group reveal"><h3>温かなひと皿</h3>${rows([['スキレット牛焼肉','700円'],['牛焼そば','700円'],['牛すじ煮・味そホルモン','各550円'],['炭焼き鳥','550円'],['赤魚煮付け','700円'],['焼魚 ホッケ','700円'],['鮭ハラス','350円'],['焼タラコ','400円']])}</section>
<section class="menu-group reveal"><h3>もう少し、ゆっくり</h3>${rows([['アヒージョ','1,000円'],['アヒージョ ハーフ','550円'],['カマンベールチーズ追加','＋100円'],['天ぷら 玉ネギ・ゴボウ（塩）','各300円'],['コロコロえび','400円'],['春雨サラダ 冷麺風','550円'],['串焼き（塩）もも・ねぎ間・レバー・皮','各150円']])}<p class="note">串焼きの注文単位などは、店内でご確認ください。</p></section>
<section class="menu-group reveal"><h3>〆と甘いもの</h3>${rows([['パスタ ハラペーニョ・ナポリタン','各700円'],['ブルーチーズ','500円'],['玉子おじや（梅干し入り）','500円'],['揚げパン','100円'],['チーズ・チョコ・ナッツ','各250円'],['フルーツパフェ','550円']])}</section></div></section>
<section class="drink-section section" id="drink"><div class="drink-photo reveal">${photo('bottles','焼酎など、玉の家のカウンターに並ぶお酒')}</div><div class="drink-copy reveal"><p class="eyebrow">YOUR FAVORITE GLASS</p><h2>一杯を、<br>自分のペースで。</h2><p>歌う前の一杯も、お料理に合わせる一杯も。<br>お好きなお酒とともに、ゆっくりお楽しみください。</p><p>お酒の種類や価格は、店内でご案内しています。<br>おすすめも、お気軽にお声がけください。</p><a class="text-link" href="${tel}">お問い合わせはこちら ${arrow}</a></div></section>
<section class="board-section section" id="blackboard"><p class="eyebrow">AT THE COUNTER</p><h2>黒板にも、おいしい出会い。</h2><p>玉の家の店内メニューをご覧いただけます。</p><details class="board-details"><summary>店内のお品書きを写真で見る <span aria-hidden="true">＋</span></summary><a href="assets/board.webp" ${ext} aria-label="お品書きの写真を別タブで大きく開く">${photo('board','玉の家の店内黒板メニュー。料理名と価格の一覧')}</a><p class="note">写真は撮影時の内容です。写真をタップすると別タブで拡大表示します。</p></details></section>`,'menu.html');
pages['karaoke.html']=document('カラオケ・店内','音響にこだわったカラオケと、全16席のアットホームな空間。カウンター8席、2名様テーブル2卓、4名様テーブル1卓。',`
${heading('KARAOKE & SPACE','カラオケ・店内','歌う人も、聴く人も、同じ輪の中。')}
<section class="karaoke-intro section"><div class="karaoke-photo reveal">${photo('karaoke','カラオケ端末と赤・白のマイク',{eager:true})}</div><div class="karaoke-copy reveal"><p class="eyebrow">LET YOUR VOICE SHINE</p><h2>その一曲が、<br>みんなの思い出に。</h2><p>気持ちよく歌っていただけるように、音響にもこだわっています。思いきり歌いたい夜も、好きな曲を聴きながら一杯楽しみたい夜も。</p><p>誰かが歌えば、自然と拍手や笑顔が生まれる。初めていらした方も、その輪に入りやすい温かな雰囲気を大切にしています。</p><div class="karaoke-note"><p>カラオケのご利用について</p><span>料金などの詳しいご案内は、お電話または店内でご確認ください。</span><a href="${tel}">${phone}</a></div></div></section>
<section class="seats-section section" id="seats"><div class="section-heading"><div><p class="eyebrow">A SMALL PLACE, A WARM WELCOME</p><h2>全16席の、<br>ちょうどいい距離。</h2></div><p>おひとりでゆっくり飲みたい方も。<br>お友達同士やグループで過ごしたい方も。</p></div><div class="seat-grid"><figure class="reveal">${photo('room','玉の家のカウンター席と店内の様子')}<figcaption><h3>カウンター</h3><span>8席</span></figcaption><p>おひとりでも、気軽に腰をおろせる場所。<br>料理や会話を楽しみながら、ご自分のペースで。</p></figure><figure class="reveal">${photo('tables','玉の家のテーブル席とカラオケモニター')}<figcaption><h3>テーブル</h3><span>2名様 × 2卓 ／ 4名様 × 1卓</span></figcaption><p>親しい人と、同じテーブルを囲んで。<br>一緒に歌って、食べて、楽しい夜を。</p></figure></div><p class="seats-note">お席の空き状況やグループでのご利用は、お電話でお気軽にご相談ください。</p></section>
<section class="welcome-section section"><img class="welcome-logo" src="assets/logo.webp" width="240" height="240" alt="玉の家のロゴ"><div><p class="eyebrow">WELCOME TO TAMANOIE</p><h2>今夜も、笑顔が集まる。</h2><p>カラオケを思いきり楽しむ夜も。<br>美味しい料理とお酒を、ゆっくり味わう夜も。<br>玉の家で、心地よいひとときをお過ごしください。</p></div></section>`,'karaoke.html');
pages['access.html']=document('店舗案内・ご予約','横浜市港北区高田東4丁目11-16 たかな橋荘101。高田駅から徒歩10分。17時から24時まで、月・木定休。電話090-5238-1332。',`
${heading('ACCESS & RESERVATION','店舗案内・ご予約','高田駅から歩いて、玉の家へ。')}
<section class="access-section section"><div class="access-photo reveal">${photo('exterior','黄色いひさしとカラオケののぼりが目印の玉の家の外観',{eager:true})}<p>黄色いひさしと「玉の家」の看板が目印です。</p></div><div class="access-info"><p class="eyebrow">IZAKAYA & KARAOKE TAMANOIE</p><h2>居酒屋カラオケ玉の家</h2><dl class="info-list"><div><dt>所在地</dt><dd>〒223-0065<br>神奈川県横浜市港北区高田東4丁目11-16<br>たかな橋荘 101</dd></div><div><dt>アクセス</dt><dd>高田駅から徒歩10分</dd></div><div><dt>営業時間</dt><dd>17:00–24:00</dd></div><div><dt>定休日</dt><dd>月曜日・木曜日</dd></div><div><dt>電話</dt><dd><a href="${tel}">${phone}</a></dd></div><div><dt>お席</dt><dd>最大16名様<br>カウンター8席<br>2名様テーブル2卓・4名様テーブル1卓</dd></div></dl><a class="button map-button" href="${map}" ${ext}>Google マップで道順を見る ${arrow}</a><p class="note">臨時のお知らせなどは、Instagramをご覧ください。</p><a class="social-link" href="${instagram}" ${ext}>${ig} Instagram ${arrow}</a></div></section>`,'access.html');
pages['404.html']=document('ページが見つかりません','居酒屋カラオケ玉の家のトップページへお戻りください。',`<section class="error-section section"><p class="eyebrow">PAGE NOT FOUND</p><h1>ページが見つかりません。</h1><p>お探しのページは移動、または削除された可能性があります。</p><a class="button" href="index.html">トップへ戻る <span aria-hidden="true">→</span></a></section>`,'404.html');
for(const [file,html] of Object.entries(pages)){
 const withSocial= file==='access.html' ? html.replace('<a class="social-link" href="'+instagram+'" '+ext+'>'+ig+' Instagram '+arrow+'</a>',socialLinks()) : html;
 await writeFile(new URL(file,out),withSocial.replace('<script src="assets/site.js"','<link rel="stylesheet" href="assets/pages.css"><link rel="preload" href="assets/brand-rounded-700.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="assets/brand-social.css"><script src="assets/site.js"'));
}
console.log('Built',Object.keys(pages).join(', '));
